- name: Install system packages
  hosts: all
  become: yes
  tasks:
    - ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
    - ansible.builtin.apt:
        name:
          - python3-kubernetes
        state: present
  tags:
    - p1
    - p2
    - p3
    - bonus

- name: Install Vagrant
  hosts: all
  become: yes
  roles:
    - role: vagrant
  tags:
    - p1
    - p2

- name: Install docker
  hosts: all
  become: yes
  roles:
    - role: geerlingguy.docker
  tags:
    - p3
    - bonus

- name: Install cluster
  hosts: all
  become: yes
  roles:
    - role: cluster
  vars:
    cluster_name: "triouS"
  tags:
    - p3
    - bonus

- name: Install ArgoCD
  hosts: all
  become: yes
  roles:
      - role: argocd
  tags:
      - p3
      - bonus
      - argocd

- name: Install Wil's app
  hosts: all
  become: yes
  roles:
    - role: dev
  tags:
    - p3
    - bonus
    - dev

- name: Install gitlab
  hosts: all
  become: yes
  roles:
    - role: gitlab
  tags:
      - bonus
      - gitlab
