apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://charts.gitlab.io/"
      chart: gitlab
      targetRevision: 8.8.1
      helm:
        parameters:
          - name: "global.hosts.domain"
            value: "example.com"
          - name: "global.hosts.externalIP"
            value: "64.226.99.156"
          - name: "certmanager-issuer.email"
            value: "triou@student.42.fr"
          - name: "global.edition"
            value: "ce"
          - name: "upgradeCheck.enabled"
            value: "false"
        values: |
          prometheus:
            install: false
          registry:
            enabled: false
          gitlab-runner:
            install: false
          gitlab:
            webservice:
              resources:
                requests:
                  memory: 512Mi
          global:
            upgradeCheck.enabled: false
            edition: "ce"
            certmanager-issuer.email: "triou@student.42.fr"
            ingress:
              configureCertmanager: false
            hosts:
              domain: "gitlab.example.com"
              externalIP: 64.226.99.156
            rails:
              extraEnv:
                MALLOC_CONF: "dirty_decay_ms:1000,muzzy_decay_ms:1000"
            monitoring:
              enabled: false
            appConfig:
              lfs:
                enabled: false
              artifact:
                enabled: false
              object_store:
                enabled: false
              sidekiq:
                memoryKiller:
                  maxRss: 2000000
                concurrency: 10
              gitaly:
                memory:
                  limit: 500Mi
                shell.concurrency:
                  - rpc: "/gitaly.SmartHTTPService/PostReceivePack"
                    max_per_repo: 13
                  - rpc: "/gitaly.SSHService/SSHUploadPack"
                    max_per_repo: 3
                cgroups:
                  repositories.count: 2
                  mountpoint: "/sys/fs/cgroup"
                  hierarchyRoot: "gitaly"
                  memoryBytes: 500000
                  cpuShares: 512
                extraEnv:
                  MALLOC_CONF: "dirty_decay_ms:1000,muzzy_decay_ms:1000"
                  GITALY_COMMAND_SPAWN_MAX_PARALLEL: 2
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
