apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://charts.gitlab.io/"
      chart: gitlab
      targetRevision: 8.8.1
      helm:
        parameters:
          - name: "global.hosts.domain"
            value: "gitlab.example.com"
          - name: "global.hosts.externalIP"
            value: "64.226.99.156"
          - name: "certmanager-issuer.email"
            value: "triou@student.42.fr"
          - name: "global.edition"
            value: "ce"
          - name: "upgradeCheck.enabled"
            value: "false"
        valueFiles:
          - values.yaml
          - $values/bonus/confs/gitlab/values.yaml
    - repoURL: https://github.com/tevariou/iot.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
