apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://charts.gitlab.io/"
      chart: gitlab/gitlab
      targetRevision: 6.11.0
      helm:
        valueFiles:
          - values.yaml
          - $values/bonus/confs/gitlab/values.yaml
    - repoURL: https://github.com/tevariou/iot.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
