global:
  upgradeCheck.enabled: false
  edition: "ce"
  certmanager-issuer.email: "triou@student.42.fr"
  hosts:
    externalIP: 64.226.99.156
  rails:
    extraEnv:
      MALLOC_CONF: "dirty_decay_ms:1000,muzzy_decay_ms:1000"
  monitoring:
    enabled: false
  appConfig:
    sidekiq:
      concurrency: 10
    gitaly:
      shell.concurrency:
        - rpc: "/gitaly.SmartHTTPService/PostReceivePack"
          max_per_repo: 13
        - rpc: "/gitaly.SSHService/SSHUploadPack"
          max_per_repo: 3
      cgroups:
        repositories.count: 2
        mountpoint: "/sys/fs/cgroup"
        hierarchyRoot: "gitaly"
        memoryBytes: 500000
        cpuShares: 512
      extraEnv:
        MALLOC_CONF: "dirty_decay_ms:1000,muzzy_decay_ms:1000"
        GITALY_COMMAND_SPAWN_MAX_PARALLEL: 2
