---
- name: Add HashiCorp repository for Vagrant
  block:
    - name: Install gnupg
      ansible.builtin.stat:
        path: /usr/share/keyrings/hashicorp-archive-keyring.gpg
      register: hashicorp_keyring

    - name: Add HashiCorp repository key
      ansible.builtin.shell: |
        wget -O - https://apt.releases.hashicorp.com/gpg | gpg --yes --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list
      when: not hashicorp_keyring.stat.exists

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: not hashicorp_keyring.stat.exists

- name: Accept virtualbox-ext-pack select license
  ansible.builtin.debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: "true"
    vtype: select

- name: Accept virtualbox-ext-pack seen license
  ansible.builtin.debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: "true"
    vtype: seen

- name: Install Vagrant and provider
  environment:
    DEBIAN_FRONTEND: noninteractive
  ansible.builtin.apt:
    name:
      - vagrant
      - build-essential
      - nfs-kernel-server
      - virtualbox
      - virtualbox-dkms
      - virtualbox-qt
      - virtualbox-guest-additions-iso
      - virtualbox-guest-utils
      - virtualbox-ext-pack
    state: present

- name: Make sure nfs kernel server is running
  ansible.builtin.systemd_service:
    state: started
    name: nfs-kernel-server