---
- name: Create dev namespace
  kubernetes.core.k8s:
    name: dev
    api_version: v1
    kind: Namespace
    state: present

- name: Install dev Wil's app
  kubernetes.core.k8s:
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: dev
        namespace: argocd
      spec:
        project: default
        source:
          repoURL: https://github.com/tevariou/triou_iot.git
          path: p3/confs/
          targetRevision: main
        destination:
          server: "https://kubernetes.default.svc"
          namespace: dev
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
            allowEmpty: true
          syncOptions:
            - CreateNamespace=true

#- name: Wait for service to be created
#  command: kubectl get svc playground-service -n dev
#  register: svc_info
#  until: svc_info is succeeded
#  retries: 10
#  delay: 60
#
#- name: Set up port forwarding with kubectl
#  ansible.builtin.shell: nohup kubectl -n dev port-forward --address="0.0.0.0" svc/playground-service "8888:8888" > /dev/null 2>&1 &
